version: "3"
services:
    redis-server:
        image: redis:latest
    node-app:
        restart: always
        build: .
        ports: 
          - 8080:8081 #ports should NOT be separated; type error is thrown